export const SINGLE_LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

export const KIDS_WORDS = [
  // Animals & Creatures
  'CAT', 'DOG', 'SUN', 'STAR', 'MOON', 'JUMP', 'PLAY',
  'TREE', 'FISH', 'BIRD', 'LION', 'BEAR', 'CAKE', 'HAPPY', 'LOVE',
  'COOL', 'HERO', 'BLUE', 'RED', 'PINK', 'GOLD', 'FAST', 'FUN',
  'SHIP', 'ROBOT', 'APPLE', 'DUCK', 'FROG', 'MILK', 'PONY', 'ZOO',
  'TIGER', 'PANDA', 'KOALA', 'SHARK', 'WHALE', 'DOLPHIN', 'EAGLE', 'FALCON',
  'ZEBRA', 'GIRAFFE', 'MONKEY', 'RABBIT', 'TURTLE', 'PENGUIN', 'DRAGON', 'UNICORN',
  'DINOSAUR', 'BUTTERFLY', 'PUPPY', 'KITTEN', 'OTTER', 'SWAN', 'OCTOPUS', 'SEAL',
  'CHEETAH', 'LEOPARD', 'GORILLA', 'HAMSTER', 'PARROT', 'TOUCAN', 'IGUANA', 'CHAMELEON',
  'LADYBUG', 'FIREFLY', 'MANATEE', 'SEAHORSE', 'STARFISH', 'JELLYFISH', 'STINGRAY',
  // Space, Planets & Cosmic Adventure
  'SPACE', 'COMET', 'GALAXY', 'ORBIT', 'ASTRO', 'ALIEN', 'NEBULA', 'ROCKET',
  'PLANET', 'COSMIC', 'MERCURY', 'VENUS', 'EARTH', 'MARS', 'SATURN', 'JUPITER',
  'URANUS', 'NEPTUNE', 'PLUTO', 'METEOR', 'SOLAR', 'LUNAR', 'COSMOS', 'VOYAGE',
  'ASTRONAUT', 'SATELLITE', 'STARLIGHT', 'HORIZON', 'ECLIPSE', 'EQUINOX', 'POLARIS', 'CRATER',
  'GRAVITY', 'SHUTTLE', 'SKYLAB', 'STATION', 'QUASAR', 'PULSAR', 'SUPERNOVA', 'CLUSTER',
  // Nature, Elements & Science Wonders
  'OCEAN', 'RIVER', 'MOUNTAIN', 'RAINBOW', 'THUNDER', 'STORM', 'SUMMER', 'WINTER',
  'SPRING', 'AUTUMN', 'BREEZE', 'FLOWER', 'GARDEN', 'FOREST', 'ISLAND', 'SUNSET',
  'GEYSER', 'GLACIER', 'VOLCANO', 'CANYON', 'DESERT', 'JUNGLE', 'SAVANNAH', 'CORAL',
  'ATOM', 'LASER', 'MAGNET', 'FOSSIL', 'CRYSTAL', 'PRISM', 'ENERGY', 'LIGHT',
  'SOUND', 'MOTION', 'SCIENCE', 'WONDER', 'NATURE', 'WEATHER', 'CLOUD', 'BREEZY',
  // Adventure, Magic & Treats
  'MAGIC', 'CASTLE', 'TREASURE', 'PIRATE', 'KNIGHT', 'WIZARD', 'QUEEN', 'KING',
  'CROWN', 'DIAMOND', 'RUBY', 'PEARL', 'SPARKLE', 'CANDY', 'COOKIE',
  'PIZZA', 'ICECREAM', 'BANANA', 'ORANGE', 'BERRY', 'CHERRY', 'SUPER', 'CHAMP',
  'WINNER', 'ROCKSTAR', 'GAMES', 'PARTY', 'SMILE', 'FRIEND', 'GLOW', 'DREAM',
  'FLIGHT', 'SOAR', 'BRAVE', 'SHINE', 'CLEVER', 'GENIUS', 'PEACE', 'JOY',
  'DONUT', 'MUFFIN', 'WAFFLE', 'BURGER', 'NOODLE', 'MELON', 'PEACH', 'HONEY',
  'SUGAR', 'COCOA', 'SNACK', 'SWEET', 'YUMMY', 'DELIGHT', 'CELEBRATE',
  // Superpowers, Music & Action
  'POWER', 'ULTRA', 'HYPER', 'SONIC', 'BLITZ', 'MIGHTY', 'SHIELD', 'VALIANT',
  'GLORY', 'HEROIC', 'GUITAR', 'DRUM', 'PIANO', 'DANCE', 'SING', 'PAINT',
  'COLOR', 'RHYTHM', 'FLUTE', 'MELODY', 'HARMONY', 'CHORUS', 'VIOLIN', 'TRUMPET',
  'SPEED', 'ZOOM', 'DASH', 'SPRINT', 'LEAP', 'BOUND', 'CLIMB', 'EXPLORE',
  // ── Islamic Words ─────────────────────────────────────────────────────────
  // Five Pillars & Core Acts of Worship
  'ISLAM', 'IMAN', 'SALAH', 'ZAKAT', 'SAWM', 'HAJJ', 'WUDU', 'TAYAMMUM',
  'FAJR', 'DHUHR', 'ASR', 'MAGHRIB', 'ISHA', 'TAHAJJUD', 'WITR', 'SUNNAH',
  'FARD', 'NAFL', 'DHIKR', 'DUA', 'TAWBAH', 'TAWAKKUL', 'SABR', 'SHUKR',
  // Allah's Beautiful Names (Al-Asma ul-Husna)
  'ALLAH', 'RAHMAN', 'RAHIM', 'MALIK', 'QUDDUS', 'SALAM', 'MUMIN', 'AZIZ',
  'JABBAR', 'MUTAKABBIR', 'KHALIQ', 'BARI', 'MUSAWWIR', 'GHAFFAR', 'QAHHAAR',
  'WAHHAB', 'RAZZAQ', 'FATTAH', 'ALIM', 'QABID', 'BASIT', 'HAFIZ', 'MUQIT',
  'HASIB', 'JALIL', 'KARIM', 'RAQIB', 'MUJIB', 'WASI', 'HAKIM', 'WADUD',
  'MAJID', 'BAITH', 'SHAHID', 'HAQQ', 'WAKIL', 'QAWI', 'MATIN', 'WALI',
  'HAMID', 'MUHSI', 'MUBDI', 'MUID', 'MUHYI', 'MUMIT', 'HAYY', 'QAYYUM',
  'AHAD', 'SAMAD', 'QADIR', 'MUQTADIR', 'MUQADDIM', 'MUAKHKHIR', 'AWWAL',
  'AKHIR', 'ZAHIR', 'BATIN', 'WALI', 'MUTAALI', 'BARR', 'TAWWAB', 'MUNTAQIM',
  'AFUW', 'RAUF', 'MALIKUL', 'DHUL', 'NAFI', 'NUR', 'HADI', 'BADI',
  // Prophets of Allah (Peace be upon them)
  'ADAM', 'IDRIS', 'NUH', 'HUD', 'SALIH', 'IBRAHIM', 'ISMAIL', 'ISHAQ',
  'YAQUB', 'YUSUF', 'LUT', 'SHUAIB', 'MUSA', 'HARUN', 'DAWUD', 'SULAIMAN',
  'AYYUB', 'YUNUS', 'ILYAS', 'ALYASA', 'DHULKIFL', 'ZAKARIYYA', 'YAHYA',
  'ISA', 'MUHAMMAD',
  // Quran, Revelation & Islamic Knowledge
  'QURAN', 'SURAH', 'AYAH', 'TAFSIR', 'TAJWEED', 'TILAWAH', 'HIFDH', 'HAFIZ',
  'HADITH', 'SUNNAH', 'FIQH', 'AQIDAH', 'TAWHID', 'SHIRK', 'KUFR', 'TAQWA',
  'ILAM', 'FATWA', 'IJTIHAD', 'IJMA', 'QIYAS', 'USUL', 'MAQASID', 'SHARIA',
  // Sacred Places & History
  'MECCA', 'MEDINA', 'KAABA', 'MASJID', 'MOSQUE', 'MINARET', 'MIHRAB', 'MIMBAR',
  'MADINAH', 'BADR', 'UHUD', 'KHANDAQ', 'TABUK', 'HUNAYN', 'TAIF', 'JERUSALEM',
  'AQSA', 'DOME', 'ZAMZAM', 'ARAFAT', 'MINA', 'MUZDALIFAH', 'SAFA', 'MARWA',
  // Islamic Virtues & Character
  'ADAB', 'AKHLAQ', 'AMANAH', 'SIDQ', 'ADALAH', 'IHSAN', 'IKHLAS', 'BIRR',
  'TAWADU', 'HILM', 'AFUW', 'RAHMA', 'ADALA', 'HAYA', 'WAFA', 'UKHUWWAH',
  'AMANA', 'ZUHD', 'QANAAH', 'SHAJA', 'MURUWWAH', 'KARAM', 'INFAQ', 'SADAQAH',
  // Islamic Celebrations & Events
  'EID', 'RAMADAN', 'IFTAR', 'SUHOOR', 'LAYLAT', 'QADR', 'FITR', 'ADHA',
  'MUBARAK', 'HIJRA', 'ISRA', 'MIRAJ', 'ASHURA', 'DHULHIJJA', 'MUHARRAM',
  // Common Islamic Phrases (romanised)
  'BISMILLAH', 'ALHAMDULILLAH', 'SUBHANALLAH', 'ALLAHU', 'AKBAR', 'INSHALLAH',
  'MASHALLAH', 'ASTAGHFIRULLAH', 'ASSALAM', 'ALAYKUM', 'JAZAKALLAH', 'BARAKALLAH',
  'HAMDULILLAH', 'AMEEN', 'YARHAMUK', 'YARHAMUKALLAH',
];
